version: "3.8"

services:
  vue:
    image: node:20-alpine
    container_name: Gluten-Free-Scanner
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - vue

networks:
  vue:
    driver: bridge
